src/components/date-range-picker/package.json, src/components/date-range-picker/styles.scss
Moved font styling to desired elements instead of on parent elements, to avoid being overwritten.
=> Minor date range picker styling tweaks

src/components/card/package.json, src/components/card/story.js, src/components/card/styles.scss
Previously, rendering the loader would push card contents down by its height.
=> Card loading positioning bugfix

src/components/toast/index.js, src/components/toast/package-lock.json, src/components/toast/package.json, src/components/toast/story.js, src/components/toast/styles.scss
- Remove table-cell centering, use flexbox instead
- Add `title` prop
- Add dismissal functionality built into the toast
=> Redesign toasts to work with absolute positioning

src/components/date-range-picker/package-lock.json, src/components/date-range-picker/package.json, src/components/input-box/index.js, src/components/input-box/styles.scss
The css in the select box would flip any icon in the input box's value. Only the caret should flip.
=> Only flip the caret icon in the input box select box

src/components/date-range-picker/package-lock.json, src/components/date-range-picker/package.json, src/components/date-range-picker/styles.scss
Right aligned date range pickers are too wide. This fixes that.
=> Adjust date range picker width

Makefile, export-variables.js
A mechanism to export all variables so that density ui can be used outside of a webpack/bundler context.
Note: This isn't an officially supported use-case, but it's been requested.
```
$ make export-variables
// Density UI variables, version 5.0.3
window['@density/ui/variables/colors.json'] = {
"grayCinder": "#222A2E",
"grayDarkest": "#4E5457",
"grayDarker": "#8E9299",
"grayDark": "#B4B8BF",
"gray": "#CBCFD6",
"grayLight": "#E8E8ED",
"grayLighter": "#F0F0F2",
"grayLightest": "#FAFAFA",
"brandPrimary": "#4198FF",
"brandSuccess": "#80CD80",
"brandDanger": "#FF5454",
"brandWarning": "#FFBA08",
"textColor": "#8E9299",
"headerColor": "#4E5457",
"inputFieldTextColor": "#CBCFD6",
"inputFieldTextActiveColor": "#4E5457"
};
window['@density/ui/variables/fonts.json'] = {
"fontBase": "\"Sailec\", …
```
=> Method to export variables for non-bundled density ui

src/components/report-time-segment-breakdown/index.js, src/components/report-time-segment-breakdown/package-lock.json, src/components/report-time-segment-breakdown/package.json
In the case of a time segment that ends at the end of the day, the <= would mean that if `end.hours()` is 23, then `i.hours()` would never make it past 23, only up to 23
=> Time segment breakdown

src/components/report-comparative-performance/index.js, src/components/report-comparative-performance/package-lock.json, src/components/report-comparative-performance/package.json
The value had `Math.round`s around them, which since the values were
always < 1 would always round to 0.
=> Adjust percentage colors to match the sign of the value

src/components/report-surpassed-capacity/index.js, src/components/report-surpassed-capacity/package-lock.json, src/components/report-surpassed-capacity/package.json
The "featured" days in the report sub header were being calculated as an offset from the start of the week. If a week had days missing due to a time segment group filter, then the day name wouldn't be calculated correctly.
Instead, calculate this value by starting at the specified `startDate` rather than the start of the week.
=> Fix an issue with the start time of metrics

src/components/dashboard-report-grid/package-lock.json, src/components/dashboard-report-grid/package.json, src/components/dashboard-report-grid/styles.scss
Previously, it was capped at 1440px. Change it to be 100%.
=> Ahange dashboard report grid max width

src/components/report-hourly-breakdown/index.js, src/components/report-hourly-breakdown/package-lock.json, src/components/report-hourly-breakdown/package.json, src/components/report-hourly-breakdown/story.js, src/components/report-hourly-breakdown/styles.scss, src/components/report-total-visits-rollup/index.js, src/components/report-total-visits-rollup/package-lock.json, src/components/report-total-visits-rollup/package.json, src/components/report-total-visits-rollup/story.js, src/components/report-utilization/index.js, src/components/report-utilization/package-lock.json, src/components/report-utilization/package.json, src/components/report-utilization/story.js, src/components/report-wrapper/index.js, src/components/report-wrapper/package-lock.json, src/components/report-wrapper/package.json, src/components/report-wrapper/story.js, src/components/report-wrapper/styles.scss
- Add a new concept that can be put into a `ReportWrapper`, a `ReportExpandController`. This concept renders an "Expand" button in the lower left corner, reserving the whole row's height for the button as discussed.
- Add an expand controller to three reports - `ReportHourlyBreakdown`, `ReportUtilization`, and `ReportTotalVisitsRollup`.
- **Question**: how do we determine if the expand button should be shown or hidden? My initial implementation adds a prop called `showExpandControl` to each, and a prop called `onReportExpand` that is called when a click occurs. I'm worried that a) by default, it isn't shown, and b) it's adding two extra props that seem like they are an implementation detail that the developer using this maybe shouldn't be concerned with. However, this is the best way I …
=> Report expanding visual implmentation

src/components/dashboard-report-grid/story.js, src/components/report-comparative-performance/index.js, src/components/report-comparative-performance/package-lock.json, src/components/report-comparative-performance/package.json, src/components/report-comparative-performance/story.js
This makes the comparative performance report extensible by enabling the pass-through of props related to time.
=> Comparative performance report - time ranges as props

src/components/report-hourly-breakdown/index.d.ts, src/components/report-hourly-breakdown/index.js, src/components/report-hourly-breakdown/package-lock.json, src/components/report-hourly-breakdown/package.json, src/components/report-hourly-breakdown/story.js
This adds two props to the hourly breakdown report, for DEN-7178
=> Add "metric" and "aggregation" props to customize hourly breakdown

package-lock.json, package.json, src/app-bar/styles.scss
At least for me in chrome, `medium` doesn't seem like a valid value
=> App bar font weight

package-lock.json, package.json, src/app-bar/styles.scss, src/card/styles.scss, src/fonts/story.js, src/fonts/styles.scss, src/toast/styles.scss
- Adds Aeonik Medium font
- Readjusts font weights to be more in line with what they "typically" should be (did a bit of research):
- Normal = `400`
- Medium / Semibold = `500`
- Bold = `600`
(`font-weight: bold` means `600`, and `font-weight: normal` means `400`)
I have a corresponding dashboard change to ensure that the font weights go along with this scale that I will be pushing up shortly.
=> Add Aeonik Medium

package-lock.json, package.json, src/app-bar/story.js, src/app-bar/styles.scss
=> Add an ellipsis to text that overflows the width of an app bar

package.json, src/switch/styles.scss, src/switch/variables.json
Now looks like this:
Accepts the same props, this is just a css change
=> Change styling of the switch to match mockups

package-lock.json, package.json, src/radio-button/index.js, src/radio-button/story.js
When `onClick` is used, a warning such as this is shown:
Also, online the consensus seems to be to use `onChange`, mostly since clicking isn't the only way one can pick a choice in a radiobutton set (keyboard, assistive technologies, etc) 
Switch the `Radiobutton` to use `onChange`, and bump the major versino as this is a breaking api change.
=> Move radiobutton from `onClick` to `onChange`

package-lock.json, package.json, src/index.js, src/toast/index.js, src/toast/story.js, src/toast/styles.scss
Toasts previously only supported one line of data. This adds a context to permit toasts to be variable height and render a variable number of lines of content.
---
=> Add multiline toast context

package-lock.json, package.json, src/radio-button/index.js, src/radio-button/story.js, src/radio-button/styles.scss
- When a radio button has no text defined, don't put a margin on its right side. This was likely an oversight when the radio button was originally implemented.
- Added a story representing this case
=> Radiobutton margin

.circleci/config.yml
More details: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420
=> Add logic to publish prereleases to `next` tag instead of `latest`

package-lock.json, package.json, src/tag-input/index.js, src/tag-input/story.js, src/tag-input/styles.scss
By default before, the wrapper div around the control always had a very
large z-index. This meant that it would often be above other controls
when they were opened, which would not be expected. To get around this,
only set the z-index to be large when the control has focus / is open.
Also adds a story for this case.
=> Tag input z-index issue

src/input-box/index.tsx
Previously, the `invalid` prop was being spread onto the `input` element
within the InputBox, which caused a react error in the console. This
change makes this not the case.
=> Ensure that InputBox's `invalid` prop is not written to the dom

.gitignore, package-lock.json, package.json, src/button/index.tsx, src/button/story.js, src/button/styles.module.scss, src/icons/index.tsx, src/icons/story.js, src/index.ts, src/input-box/index.tsx, src/input-box/story.js, src/input-box/styles.module.scss, src/space-picker/index.tsx, src/space-picker/story.js, src/space-picker/styles.module.scss, variables/fonts.json, variables/fonts.scss
- Port over the space picker from the dashboard
- Add a new `leftIcon` and `rightIcon` props to the button so that an icon can be rendered on the left and right of a button. This works similarly to the existing `leftIcon` prop on the `InputBox`, and matches the styling of the most up to date sketch density ui button placement:
- Adds some new font variables that define font weights. I pushed for this a while back when the the colors were redone, but it was forgotten about. I don't think this is controversial though.
**NOTE: The package version still needs to be updated.**
=> Space picker port, button icon props, and font weight variables

package-lock.json, package.json, src/dialog/index.tsx, src/dialog/story.js, src/dialog/styles.module.scss, src/dialogger/index.tsx, src/dialogger/story.tsx, src/index.ts, src/toast/story.js, src/toaster/README.md, src/toaster/index.tsx, src/toaster/story.js
Implements all the dialog implementations in the dashboard within Density UI. Effectively, these are opinionated modals that make rendering alerts, confirm boxes, and prompts easier:
Brings over the concepts of the toaster and dialogger from the dashboard. These primitives allow for dialogs and toasts to be created imperatively, which often fits better with the way they are used within interfaces. Both of these are "singleton components" - ie, they are rendered once at the root of the app. They each have static methods on them for creating toasts and dialogs - these being `Toaster.showToast` and `Dialogger.alert` / `Dialogger.confirm` / `Dialogger.prompt`. See the stories in the diff for a usage example of each.
=> Dialogs, and Toaster / Dialogger

src/dialog/index.tsx, src/dialogger/story.tsx
This was a feature request from #406. Adds a flag so that when enabled, a prompt can only be submitted when text is entered into the text box.
=> Add ability to make dialogger prompt that requires input

package-lock.json, src/environment-switcher/index.tsx, src/environment-switcher/story.tsx
Hey @1egoman 
Here are a couple suggested tweaks.
I re-ordered the generics so that G (global) comes first, that way L (local) and C (custom) can extend G, without having to repeatedly use `& G` inside the implementation. I also made some named types for {Local,Custom}EnvironmentConfigurationBase so that they can be extended in the generics. I think it cleans it up a bit and makes it more readable, and still passes through the correct types.
Let me know what you think, these are just suggestions.
=> Suggested typing changes

package.json, src/space-picker/index.tsx, src/space-picker/story.js
There's a bug with space picker and multiselect where if we:
1. Select the first space from the current space list, then
2. Filter the list to a view without the first space, then
3. Select another space from the filtered list
There will be an error because at step 3, we try to get the `space_id` of selected spaces by mapping them to the filtered space list -- which doesn't include the first space.
Fixed this by creating another new or the filtered view (`filteredFormattedHierarchy`) and keeping the original list intact.
Closes [PRD-489](https://densityio.atlassian.net/browse/PRD-489).
=> Fix space picker bug with multi-select in a filtered view

package-lock.json, package.json, src/space-picker/index.tsx, src/space-picker/story.js
Adds a prop, `autoSelectChildren`, to the SpacePicker and SpacePickerDropdown. When set to `true`, the picker should ergonomically auto-select or auto-deselect the children of a space.
Requires `canSelectMultiple` to be true for this behavior to apply.
=> PRD-2143: auto-select children setting

package-lock.json, package.json, src/icons/index.tsx, src/icons/symbols/snap-grid.tsx
I had Aglae make me a new icon for use in planner:
=> BOOTS-164: add new "snap grid" icon
