src/components/date-picker/package.json
src/components/date-picker/styles.scss
src/components/date-range-picker/package.json
src/components/date-range-picker/styles.scss

- Fixes input padding on both date-picker and date-range-picker
- Fixes an aliasing issue w/ the common range icon

Date selection style tweaks

---

LICENSE.md
src/components/card/index.js
src/components/card/package-lock.json
src/components/card/package.json
src/components/card/story.js
src/components/card/styles.scss

Card well, dark varient

---

src/components/card/package-lock.json
src/components/card/package.json
src/components/card/styles.scss
src/components/icons/package-lock.json
src/components/icons/story.js
src/components/input-box/index.js
src/components/input-box/package-lock.json
src/components/input-box/package.json
src/components/input-box/story.js
src/components/input-box/styles.scss

Custom select box!

---

src/components/switch/index.js
src/components/switch/package-lock.json
src/components/switch/package.json
src/components/switch/stories.js
src/components/switch/styles.scss

Add disabled switch state

---

src/components/input-box/index.js
src/components/input-box/package-lock.json
src/components/input-box/package.json
src/components/input-box/story.js
src/components/input-box/styles.scss

Fixes some behavior bugs around closing the input-box dropdown.

ISGT-66 and ISGT-68

---

src/components/switch/index.js
src/components/switch/package-lock.json
src/components/switch/package.json
src/components/switch/stories.js

Update the switch to use `value` instead of `enabled` to control its switched state.

Switch value prop

---

src/components/input-stack/package-lock.json
src/components/input-stack/package.json
src/components/input-stack/styles.scss

Cross-browser css work needed for planner to work well on ipad

Add some css to make it work better on safari

---

src/components/input-box/index.js
src/components/input-box/package-lock.json
src/components/input-box/package.json
src/components/input-box/styles.scss
src/components/input-stack/package-lock.json
src/components/input-stack/package.json
src/components/input-stack/styles.scss

Change default placeholder color on textboxes

---

src/components/date-picker/index.js
src/components/date-picker/package-lock.json
src/components/date-picker/package.json
src/components/date-picker/story.js
src/components/date-picker/styles.scss
src/components/date-range-picker/package-lock.json
src/components/input-box/package-lock.json

Allows a user to move from day-to-day quickly, without opening up the calendar.

Date picker paging arrows

---

src/components/date-picker/package-lock.json
src/components/date-picker/package.json
src/components/date-picker/styles.scss

Left and right align date picker popup with main element

---

src/components/template/index.js
src/components/template/styles.scss

Update template convention to work with css modules

Template convention

---

src/components/report-hourly-breakdown/index.js
src/components/report-hourly-breakdown/package.json
src/components/report-hourly-breakdown/story.js
src/components/report-hourly-breakdown/styles.scss

Add report hourly breakdown report interface

---

src/components/report-wasted-space/index.js
src/components/report-wasted-space/package-lock.json
src/components/report-wasted-space/package.json
src/components/report-wasted-space/story.js
src/components/report-wasted-space/styles.scss

- Add small text above bars when they collapse below 50px
- Maybe we should make this more dynamic, but I'm fine with this at
the moment.
- Make props functional

Finish up wasted space report

---

src/components/report-wrapper/package-lock.json
src/components/report-wrapper/package.json
src/components/report-wrapper/styles.scss

Add overflow hidden to the report wrapper

---

package-lock.json
package.json
src/input-box/index.js
src/input-box/story.js
src/input-box/styles.scss

- Add `placeholder` prop to pass through custom placeholder
- Add optional prop `menuMaxHeight` to define how tall the menu can be at maximum, this is required for really long lists of stuff
- Add stories for these two cases

Select box changes

---

package-lock.json
package.json
src/date-picker/styles.scss
src/date-range-picker/styles.scss

I forgot to adjust the border on the date picker to match the input boxes, oops

Date picker border

---

package-lock.json
package.json
src/fonts/styles.scss

Originally, there was a `:global` around the font face. Because of https://github.com/css-modules/css-modules/issues/95, I removed it, and now the font seems to work.

Unwrap font face

---

package-lock.json
package.json
src/input-box/index.js
src/input-box/story.js
src/input-box/styles.scss
webpack.config.js

@guscost Feel free to make any pixel-related adjustments, but these are pretty good as far as I'm concerned.

Input boxes

---

package-lock.json
package.json
src/input-box/styles.scss

Increase font size in select box to 16px

---

package-lock.json
package.json
src/button/index.js
src/button/story.js
src/button/styles.scss
src/input-box/styles.scss

New Button

---

package-lock.json
package.json
src/icons/index.js

Modify the folder icon to use the specified color

Folder icon color

---

package-lock.json
package.json
src/button/index.js
src/button/story.js

Make a new instance of the `DIGEST_DELETE_BUTTON` for the user management page, called `USER_MANAGEMENT_DETAIL_DELETE_BUTTON`.

User management delete button

---

.storybook/config.js
.storybook/styles.scss
package-lock.json
package.json
src/index.js
src/modal/README.md
src/modal/index.js
src/modal/story.js
src/modal/styles.scss
src/skeleton/README.md
src/skeleton/index.js
src/skeleton/story.js
src/skeleton/styles.scss
src/toast/README.md
src/toast/index.js
src/toast/story.js
src/toast/styles.scss

- Port `modal`, `toast`, and `skeleton` to Density UI from the Dashboard.

Modal, toast, and skeleton

---

package-lock.json
package.json
src/app-sidebar/index.js
src/app-sidebar/story.js
src/app-sidebar/styles.scss

This allows a user to specify a wider sidebar than normal. Also adds two stories exercising this new prop.

Add width prop to app sidebar

---

src/toast/story.js
src/toast/styles.scss

At some point, toast animating in / out broke. I tried to get it to work
with the existing css animations but couldn't, so I switched to using a
css transition. Also added a story for this case so we can avoid it
happening in the future.

Fix animation issue with toast

---

package-lock.json
package.json

Bump node-sass to work with node `v12.x.x`

Bump node-sass

---

package-lock.json
package.json
src/date-picker/index.js
src/date-picker/story.js
src/date-picker/styles.scss
src/index.js
src/input-box/index.js
src/input-box/story.js
src/input-box/styles.scss
src/list-view/index.js
src/list-view/story.js
src/list-view/styles.module.scss

Ported from @1egoman 's experiment with draggable rows: https://github.com/DensityCo/dashboard/commit/4f246c84999fa724375c5db64758fc333a72db1c#diff-4ed48d4c78a0e18f22304132b8709727R92
Nice solution for the table-and-column API, this allows us to render normal tables or anything else! We'll lose the column "flexboxiness" with this table implementation, but it's a known tradeoff that @rjgrazioli has approved.

Implement ListView w/ table

---

package.json
src/date-range-picker/index.js
src/date-range-picker/story.js
src/index.js

Add context for small width date range picker.

Add small width date picker

---

package-lock.json
package.json
src/day-of-week-picker/README.md
src/day-of-week-picker/index.js
src/day-of-week-picker/story.js
src/day-of-week-picker/styles.scss
src/index.js

I copied this from the dashboard, as it will be needed in another external project soon.

Add new day of week picker control

---

package-lock.json
package.json
src/checkbox/README.md
src/checkbox/index.js
src/checkbox/story.js
src/checkbox/styles.module.scss

Add checkbox to density ui

---

package-lock.json
package.json
src/input-box/index.tsx

Reverts DensityCo/ui#239
Turns out I'm just a bad speller. Above, there is the `...props` which handles this case.

Revert "Add placeholder to textarea"

---

package-lock.json
package.json
src/date-range-picker/styles.module.scss
src/day-of-week-picker/styles.module.scss
src/input-box/styles.module.scss
src/pager-button-group/index.tsx
src/pager-button-group/styles.module.scss

- Fixed pagination so that it didn't always look disabled
- Updated date picker colors to match comps
- Updated select list items to match comps

PRD-160/dashboard doorway nitpicks

---

package-lock.json
package.json
src/dialogger/index.tsx
src/toaster/index.tsx

This are issues the dashboard showed, but this project did not. I don't know why this is.

Issues with toaster and dialogger types

---

package-lock.json
package.json
src/icons/index.tsx
src/icons/symbols/dots.tsx

Adding a new icon to use in displays.

Add dots icon

---

src/navbar/index.tsx
src/navbar/story.js
src/navbar/styles.module.scss

Copying over the navbar component that @guscost made.

Add navbar component

---

package-lock.json
package.json
src/navbar/styles.module.scss

- Change navbar width to account for padding
- Move the Beta tag down for some top padding

Navbar styling

---

package.json
src/date-range-picker/index.tsx
src/date-range-picker/story.js

Feat no header date range picker context

---

package.json
src/navbar/index.tsx
src/navbar/story.js

Use the `showOpenArea` prop to determine if open area should be visible in navbar.

Conditional Open Area Tab
